name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
         DATABASE_URL: ${{ secrets.DATABASE_URL }}
         BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
         BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
         CI: true
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30